name: Maven build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - README.md
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
      - name: Report tests
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: JUnit Tests
          working-directory: 'target/surefire-reports'
          path: TEST-*.xml
          reporter: java-junit
          only-summary: 'true'
